// Auto-generated by scripts/extract_mrl_inmoov.py — do not edit by hand.
#pragma once

#define SERVO_COUNT 36

const uint8_t SERVO_PINS[SERVO_COUNT] PROGMEM = {3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38};
const uint8_t SERVO_MIN[SERVO_COUNT] PROGMEM = {0, 60, 0, 0, 0, 60, 0, 0, 40, 0, 0, 0, 0, 40, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
const uint8_t SERVO_MAX[SERVO_COUNT] PROGMEM = {180, 120, 40, 180, 180, 130, 180, 180, 180, 90, 180, 180, 180, 180, 90, 180, 180, 180, 180, 180, 180, 180, 180, 180, 180, 180, 180, 180, 160, 180, 180, 180, 180, 160, 180, 180};
const uint8_t SERVO_REST[SERVO_COUNT] PROGMEM = {85, 90, 8, 60, 50, 120, 90, 45, 90, 90, 90, 90, 45, 90, 90, 90, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 90, 90, 10, 90, 90, 90, 90, 10, 90, 90};
const uint8_t SERVO_EASE[SERVO_COUNT] PROGMEM = {20, 18, 56, 15, 13, 18, 20, 18, 20, 20, 18, 20, 18, 20, 20, 18, 38, 38, 38, 38, 38, 38, 38, 38, 38, 38, 15, 15, 13, 15, 15, 15, 15, 13, 15, 15};

#define PATTERN_COUNT 6

struct PatternStep {
  int8_t vals[6];  // head_neck, eye, jaw, rot, tilt, roll (-1 = skip)
  uint16_t holdMs;
};

struct PatternDef {
  const char* name;
  const PatternStep* steps;
  uint8_t stepCount;
};

const PatternStep PATTERN_NOD_STEPS[] PROGMEM = {
  {{85, 90, 8, 60, 80, 120}, 600},
  {{85, 90, 8, 60, 20, 120}, 600},
  {{85, 90, 8, 60, 50, 120}, 400},
};

const PatternStep PATTERN_SHAKE_STEPS[] PROGMEM = {
  {{85, 60, 8, 10, 50, 170}, 600},
  {{85, 120, 8, 110, 50, 70}, 600},
  {{85, 90, 8, 60, 50, 120}, 400},
};

const PatternStep PATTERN_YES_STEPS[] PROGMEM = {
  {{85, 90, 8, 60, 35, 120}, 400},
  {{85, 90, 8, 60, 70, 120}, 400},
  {{85, 90, 8, 60, 35, 120}, 400},
  {{85, 90, 8, 60, 50, 120}, 300},
};

const PatternStep PATTERN_NO_STEPS[] PROGMEM = {
  {{85, 60, 8, 25, 50, 150}, 400},
  {{85, 120, 8, 95, 50, 90}, 400},
  {{85, 60, 8, 25, 50, 150}, 400},
  {{85, 90, 8, 60, 50, 120}, 300},
};

const PatternStep PATTERN_BOW_STEPS[] PROGMEM = {
  {{85, 90, 8, 60, 50, 120}, 500},
  {{85, 90, 10, 60, 15, 120}, 1200},
  {{85, 90, 8, 60, 50, 120}, 500},
};

const PatternStep PATTERN_RELAX_STEPS[] PROGMEM = {
  {{85, 90, 8, 60, 50, 120}, 300},
};

const PatternDef PATTERNS[PATTERN_COUNT] PROGMEM = {
  {"nod", PATTERN_NOD_STEPS, 3},
  {"shake", PATTERN_SHAKE_STEPS, 3},
  {"yes", PATTERN_YES_STEPS, 4},
  {"no", PATTERN_NO_STEPS, 4},
  {"bow", PATTERN_BOW_STEPS, 3},
  {"relax", PATTERN_RELAX_STEPS, 1},
};
